In [2]:
# 1. Create a null vector of size 10 but the fifth value which is 1.
import numpy as np
null_vector = np.zeros(10,dtype=int)
null_vector[4] = 1
null_vector


array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [3]:
# 2. Create a vector with values ranging from 10 to 49.
import numpy as np
vector = np.arange(10,50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8

import numpy as np
matrix = np.arange(0, 9).reshape((3, 3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]

import numpy as np
arrayy = np.array([1,2,0,0,4,0])
indices = np.nonzero(arrayy)
indices

(array([0, 1, 4], dtype=int64),)

In [16]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np 
arrayy = np.random.rand(10,10)
min_val = np.min(arrayy)
max_val = np.max(arrayy)
print("Minimum value:", min_val)
print("Maximum value:", max_val)



Minimum value: 0.0035393974245983006
Maximum value: 0.9954851351954251


In [18]:
# 6.Create a random vector of size 30 and find the mean value.
import numpy as np
vect = np.random.rand(30)
mean = np.mean(vect)
mean

0.48102140004300475